export type ShippingConfig = typeof shippingConfig;
export type County = ShippingConfig["county"][number];
export type SubCounty = County["subCounty"][number];

export const shippingConfig = {
  county: [
    {
      name: "Mombasa",
      subCounty: [
        { name: "Changamwe", ward: ["Port Reitz", "Kipevu", "Airport", "Chaani"] },
        { name: "Jomvu", ward: ["Jomvu Kuu", "Miritini", "Mikindani"] },
        { name: "Kisauni", ward: ["Mjambere", "Junda", "Bamburi", "Mwakirunge"] },
        { name: "Nyali", ward: ["Frere Town", "Ziwa La Ng'ombe", "Mkomani", "Kongowea"] },
        { name: "Likoni", ward: ["Mtongwe", "Shika Adabu", "Bofu", "Likoni"] },
        { name: "Mvita", ward: ["Mji wa Kale", "Tudor", "Tononoka", "Shimanzi"] },
      ],
    },
    {
      name: "Kwale",
      subCounty: [
        { name: "Msambweni", ward: ["Gombato Bongwe", "Ukunda", "Kinondo"] },
        { name: "Lunga Lunga", ward: ["Pongwe Kikoneni", "Dzombo", "Mwereni"] },
        { name: "Matuga", ward: ["Tsimba Golini", "Waa", "Tiwi", "Kubo South"] },
        { name: "Kinango", ward: ["Ndavaya", "Puma", "Kinango", "Mackinnon Road"] },
      ],
    },
    {
      name: "Kilifi",
      subCounty: [
        { name: "Kilifi North", ward: ["Tezo", "Sokoni", "Kibarani", "Watamu"] },
        { name: "Kilifi South", ward: ["Chasimba", "Mtwapa", "Mtepeni", "Shariani"] },
        { name: "Malindi", ward: ["Jilore", "Kakuyuni", "Ganda", "Malindi Town"] },
        { name: "Magarini", ward: ["Marafa", "Magarini", "Gongoni", "Adu"] },
        { name: "Ganze", ward: ["Ganze", "Bamba", "Jaribuni", "Sokoke"] },
      ],
    },
    {
      name: "Tana River",
      subCounty: [
        { name: "Garsen", ward: ["Kipini East", "Kipini West", "Garsen Central"] },
        { name: "Galole", ward: ["Kinakomba", "Mikinduni", "Wayu"] },
        { name: "Bura", ward: ["Chewele", "Hirimani", "Bangale"] },
      ],
    },
    {
      name: "Lamu",
      subCounty: [
        { name: "Lamu East", ward: ["Faza", "Kiunga", "Basuba"] },
        { name: "Lamu West", ward: ["Shella", "Mkomani", "Hindi", "Mkunumbi"] },
      ],
    },
    {
      name: "Taita Taveta",
      subCounty: [
        { name: "Taveta", ward: ["Chala", "Mahoō", "Bura", "Mboghoni"] },
        { name: "Wundanyi", ward: ["Wundanyi/Mbale", "Werugha", "Mgange"] },
        { name: "Mwatate", ward: ["Ronge", "Mwatate", "Bura", "Chawia"] },
        { name: "Voi", ward: ["Mbololo", "Sagalla", "Kaloleni", "Ngolia"] },
      ],
    },
    {
      name: "Garissa",
      subCounty: [
        { name: "Garissa Township", ward: ["Waberi", "Galbet", "Township", "Iftin"] },
        { name: "Balambala", ward: ["Balambala", "Danyere", "Jarajara"] },
        { name: "Lagdera", ward: ["Modogashe", "Benane", "Goreale"] },
        { name: "Dadaab", ward: ["Dertu", "Dadaab", "Labasigale"] },
        { name: "Fafi", ward: ["Bura", "Dekaharia", "Jarajilla"] },
        { name: "Ijara", ward: ["Ijara", "Sangailu", "Masalani"] },
      ],
    },
    {
      name: "Wajir",
      subCounty: [
        { name: "Wajir North", ward: ["Gurar", "Bute", "Korondile", "Malkagufu"] },
        { name: "Wajir East", ward: ["Wagalla", "Township", "Barwaqo", "Khorof-Harar"] },
        { name: "Wajir South", ward: ["Benane", "Burder", "Dadajabula", "Habaswein"] },
        { name: "Wajir West", ward: ["Arbajahan", "Hadado", "Ademasajide"] },
        { name: "Eldas", ward: ["Eldas", "Della", "Lakoley South"] },
        { name: "Tarbaj", ward: ["Elben", "Sarman", "Tarbaj", "Wargadud"] },
      ],
    },
    {
      name: "Mandera",
      subCounty: [
        { name: "Mandera West", ward: ["Takaba South", "Takaba", "Lagsure"] },
        { name: "Mandera North", ward: ["Ashabito", "Guticha", "Morothile"] },
        { name: "Mandera South", ward: ["Wargadud", "Kutulo", "Elwak South"] },
        { name: "Mandera East", ward: ["Arabia", "Township", "Neboi", "Khalalio"] },
        { name: "Lafey", ward: ["Fino", "Lafey", "Waranqara"] },
        { name: "Banissa", ward: ["Banissa", "Derkhale", "Malkamari"] },
      ],
    },
    {
      name: "Marsabit",
      subCounty: [
        { name: "Moyale", ward: ["Butiye", "Sololo", "Heillu Manyatta", "Golbo"] },
        { name: "North Horr", ward: ["Dukana", "Maikona", "North Horr", "Illeret"] },
        { name: "Saku", ward: ["Sagate/Jaldesa", "Karare", "Marsabit Central"] },
        { name: "Laisamis", ward: ["Loiyangalani", "Kargi/South Horr", "Koris"] },
      ],
    },
    {
      name: "Isiolo",
      subCounty: [
        { name: "Isiolo", ward: ["Wabera", "Bulla Pesa", "Burat", "Ngaremara", "Oldo/Nyiro"] },
        { name: "Garbatulla", ward: ["Garbatulla", "Kina", "Sericho"] },
        { name: "Merti", ward: ["Cherab", "Chari"] },
      ],
    },
    {
      name: "Meru",
      subCounty: [
        { name: "Imenti North", ward: ["Municipality", "Ntunene", "Nyaki West", "Nyaki East"] },
        { name: "Imenti South", ward: ["Mitunguu", "Igoji East", "Igoji West", "Abogeta East", "Abogeta West"] },
        { name: "Buuri", ward: ["Timau", "Kisima", "Kiirua/Naari", "Ruiri/Rwarera"] },
        { name: "Tigania East", ward: ["Mikinduri", "Kiguchwa", "Muthara", "Karama"] },
        { name: "Tigania West", ward: ["Athwana", "Akithi", "Kianjai", "Nkomo", "Mbeu"] },
        { name: "Igembe North", ward: ["Antuambui", "Ntunene", "Antubetwe Kiongo", "Naathu", "Amwathi"] },
        { name: "Igembe Central", ward: ["Akirang'ondu", "Athiru Ruujine", "Igembe East", "Njirrine", "Kangeta"] },
        { name: "Igembe South", ward: ["Maua", "Kiegoi/Antubochiu", "Athiru Gaiti", "Akachiu", "Kanuni"] },
      ],
    },
    {
      name: "Tharaka-Nithi",
      subCounty: [
        { name: "Chuka", ward: ["Mariani", "Karingani", "Magumoni", "Mugwe"] },
        { name: "Maara", ward: ["Mitheru", "Muthambi", "Mwimbi", "Ganga", "Chogoria"] },
        { name: "Tharaka", ward: ["Gatunga", "Mukothogodo", "Nkondi", "Chiakariga", "Marimanti"] },
      ],
    },
    {
      name: "Embu",
      subCounty: [
        { name: "Manyatta", ward: ["Ruguru/Ngandori", "Kithimu", "Nginda", "Mbeti North", "Kirimari"] },
        { name: "Runyenjes", ward: ["Gaturi South", "Kagaari South", "Kagaari North", "Central Ward", "Kyeni North", "Kyeni South"] },
        { name: "Mbeere South", ward: ["Mwea", "Makima", "Mbeti South", "Mavuria", "Kiambere"] },
        { name: "Mbeere North", ward: ["Nthawa", "Muminji", "Evurore"] },
      ],
    },
    {
      name: "Kitui",
      subCounty: [
        { name: "Kitui Central", ward: ["Miwani", "Township", "Mulango", "Kyangwithya West", "Kyangwithya East"] },
        { name: "Kitui West", ward: ["Mutonguni", "Kauwi", "Matinyani", "Kwa Mutonga/Kithumula"] },
        { name: "Kitui Rural", ward: ["Kisasi", "Mbitini", "Mui", "Voo/Kyamatu"] },
        { name: "Kitui South", ward: ["Ikutha", "Mutomo", "Mutha", "Kaniko/Ikana", "Kanziko"] },
        { name: "Mwingi North", ward: ["Ngomeni", "Kyuso", "Mumoni", "Tseikuru", "Tharaka"] },
        { name: "Mwingi West", ward: ["Kyome/Thaana", "Nguutani", "Migwani", "Kiomo/Kyethani"] },
        { name: "Mwingi Central", ward: ["Central", "Kivou", "Nguni", "Nuu", "Mui", "Waita"] },
      ],
    },
    {
      name: "Machakos",
      subCounty: [
        { name: "Machakos Town", ward: ["Kalama", "Muputi", "Mumbuni North", "Macha Town", "Muvuti/Kiima-Kimwe"] },
        { name: "Mavoko", ward: ["Athi River", "Syokimau/Mlolongo", "Upper Katani", "Kinanie/Muthwani"] },
        { name: "Yatta", ward: ["Ndalani", "Matuu", "Kithimani", "Ikombe", "Katangi"] },
        { name: "Masinga", ward: ["Kivaa", "Masinga Central", "Ekalakala", "Muthesya", "Ndithini"] },
        { name: "Matungulu", ward: ["Tala", "Matungulu North", "Matungulu East", "Matungulu West", "Kyeleni"] },
        { name: "Kangundo", ward: ["Kangundo North", "Kangundo Central", "Kangundo East", "Kangundo West"] },
        { name: "Kathiani", ward: ["Mitaboni", "Kathiani Central", "Upper Kaewa/Iveti"] },
        { name: "Mwala", ward: ["Mbiuni", "Makutano/Mwala", "Masii", "Muthetheni", "Wamunyu", "Kibauni"] },
      ],
    },
    {
      name: "Makueni",
      subCounty: [
        { name: "Makueni", ward: ["Wote", "Muvau/Kikumini", "Mavindini", "Kitise/Kithuki", "Kathonzweni", "Nzaui/Kilili/Kalamba"] },
        { name: "Mbooni", ward: ["Mbooni", "Kithungo/Kitundu", "Tulimani", "Kisau/Kiteta", "Kako/Waia", "Kalawa"] },
        { name: "Kibwezi East", ward: ["Masongaleni", "Mtito Andei", "Thange", "Ivingoni/Nzambani"] },
        { name: "Kibwezi West", ward: ["Makindu", "Nguu/Masumba", "Emali/Mulala"] },
        { name: "Kaiti", ward: ["Ukia", "Kee", "Kilala/Gaitei", "Ilima"] },
        { name: "Kilome", ward: ["Kasikeu", "Mukaa", "Kiima Kiu/Kalanzoni"] },
      ],
    },
    {
      name: "Nyandarua",
      subCounty: [
        { name: "Ol Kalou", ward: ["Karau", "Kanjuiri Ridge", "Kaimbaga", "Tower"] },
        { name: "Ol Joro Orok", ward: ["Gathanji", "Gatimu", "Weru", "Charagita"] },
        { name: "Ndaragwa", ward: ["Leshau/Pondo", "Kiriita", "Central", "Shamata"] },
        { name: "Kipipiri", ward: ["Wanjohi", "Kipipiri", "Geta", "Githioro"] },
        { name: "Kinangop", ward: ["Engineer", "Gathara", "North Magumu", "Njabini\Kiburu", "Nyakio", "Githabeni"] },
      ],
    },
    {
      name: "Nyeri",
      subCounty: [
        { name: "Nyeri Town", ward: ["Kiganjo/Mathari", "Rware", "Gatitu/Muruguru", "Ruring'u", "Kamakwa/Mukaro"] },
        { name: "Othaya", ward: ["Mahiga", "Iria-Ini", "Chinga", "Karima"] },
        { name: "Mathira", ward: ["Ruguru", "Magutu", "Iria-Ini", "Kirimukuyu", "Konyu"] },
        { name: "Tetu", ward: ["Dedan Kimathi", "Wamagana", "Aguthi-Gaaki"] },
        { name: "Mukurwe-ini", ward: ["Gikondi", "Rugi", "Mukurwe-ini West", "Mukurwe-ini Central"] },
        { name: "Kieni", ward: ["Mweiga", "Naro Moru/Nairutia", "Theuri", "Gatarakwa", "Mugunda", "Gakawa"] },
      ],
    },
    {
      name: "Kirinyaga",
      subCounty: [
        { name: "Mwea East", ward: ["Tebere", "Nyangati", "Murinduko", "Gathigiriri"] },
        { name: "Mwea West", ward: ["Mutithi", "Kangai", "Thiba", "Wamumu"] },
        { name: "Kirinyaga Central", ward: ["Mutira", "Kanyekini", "Kerugoya", "Inoi"] },
        { name: "Kirinyaga East", ward: ["Kabare", "Baragwi", "Njukiini", "Ngariama", "Karumandi"] },
        { name: "Kirinyaga West", ward: ["Kiine", "Mukure", "Kariti"] },
      ],
    },
    {
      name: "Murang'a",
      subCounty: [
        { name: "Kiharu", ward: ["Wangu", "Mugoiri", "Mbiri", "Township", "Murarandia", "Gaturi"] },
        { name: "Kangema", ward: ["Kanyenyaini", "Muguru", "Rwathia"] },
        { name: "Mathioya", ward: ["Gitugi", "Kiru", "Kamacharia"] },
        { name: "Gatanga", ward: ["Ithiru", "Jugini", "Gatanga", "Kariara", "Mugumo-ini", "Kakuzi/Mitubiri"] },
        { name: "Kandara", ward: ["Ng'araria", "Muruka", "Kagundu-ini", "Gaichanjiru", "Ithiru", "Ruchu"] },
        { name: "Kigumo", ward: ["Kahumbu", "Muthithi", "Kigumo", "Kangari", "Kinyona"] },
        { name: "Maragua", ward: ["Kimorori/Wempa", "Makuyu", "Kambiti", "Kamahuha", "Ichagaki", "Nginda"] },
      ],
    },
    {
      name: "Kiambu",
      subCounty: [
        { name: "Kiambu Town", ward: ["Ting'ang'a", "Ndumberi", "Riabai", "Township"] },
        { name: "Ruiru", ward: ["Gitothua", "Biashara", "Gatongora", "Kahawa Sukari", "Kahawa Wendani", "Kiuu", "Mwiki", "Mwihoko"] },
        { name: "Thika Town", ward: ["Township", "Kamenu", "Hospital", "Gatuanyaga", "Ngoliba"] },
        { name: "Juja", ward: ["Murera", "Theta", "Juja", "Witeithie", "Kalimoni"] },
        { name: "Kikuyu", ward: ["Nachu", "Karai", "Kikuyu", "Sigona", "Kinoo"] },
        { name: "Kabete", ward: ["Gitaru", "Muguga", "Nyathuna", "Kabete", "Uthiru"] },
        { name: "Limuru", ward: ["Bibirioni", "Limuru Central", "Ndeiya", "Limuru East", "Tigoni/Ngecha"] },
        { name: "Lari", ward: ["Kinale", "Kijabe", "Nyanduma", "Kamburu", "Lari/Kirenga"] },
        { name: "Gatundu South", ward: ["Kiamwangi", "Kiganjo", "Ndarugu", "Ngenda"] },
        { name: "Gatundu North", ward: ["Gituamba", "Githobokoni", "Chania", "Mang'u"] },
        { name: "Githunguri", ward: ["Githunguri", "Githiga", "Ikinu", "Ngewa", "Komothai"] },
        { name: "Kiambaa", ward: ["Cianda", "Karuri", "Ndenderu", "Muchatha", "Kihara"] },
      ],
    },
    {
      name: "Nairobi",
      subCounty: [
        { name: "Westlands", ward: ["Kitisuru", "Parklands/Highridge", "Karura", "Kangemi", "Mountain View"] },
        { name: "Dagoretti North", ward: ["Kilimani", "Kawangware", "Gatina", "Kileleshwa", "Kabiro"] },
        { name: "Dagoretti South", ward: ["Mutu-ini", "Ngando", "Riruta", "Uthiru/Ruthimitu", "Waithaka"] },
        { name: "Lang'ata", ward: ["Karen", "Nairobi West", "Mugumo-ini", "South C", "Nyayo Highrise"] },
        { name: "Kibra", ward: ["Laini Saba", "Lindi", "Makina", "Woodley/Kenyatta Golf Course", "Sarang'ombe"] },
        { name: "Roysambu", ward: ["Roysambu", "Garden Estate", "Ridgeways", "Kahawa West", "Zimmerman", "Kahawa"] },
        { name: "Kasarani", ward: ["Clay City", "Mwiki", "Kasarani", "Njiru", "Ruirai"] },
        { name: "Ruaraka", ward: ["Baba Dogo", "Utalii", "Mathare North", "Lucky Summer", "Korogocho"] },
        { name: "Embakasi South", ward: ["Imara Daima", "Kwa Njenga", "Kwa Reuben", "Pipeline", "Kware"] },
        { name: "Embakasi North", ward: ["Kariobangi North", "Dandora Area I", "Dandora Area II", "Dandora Area III", "Dandora Area IV"] },
        { name: "Embakasi Central", ward: ["Kayole North", "Kayole Central", "Kayole South", "Komo Rock", "Matopeni/Spring Valley"] },
        { name: "Embakasi East", ward: ["Upper Savanna", "Lower Savanna", "Embakasi", "Utawala", "Mihang'o"] },
        { name: "Embakasi West", ward: ["Umoja I", "Umoja II", "Mowlem", "Kariobangi South"] },
        { name: "Makadara", ward: ["Maringo/Hamza", "Viwandani", "Harambee", "Makongeni"] },
        { name: "Kamukunji", ward: ["Pumwani", "Eastleigh North", "Eastleigh South", "Airbase", "California"] },
        { name: "Starehe", ward: ["Nairobi Central", "Ngara", "Pangani", "Ziwani/Kariokor", "Landimawe", "Nairobi South"] },
        { name: "Mathare", ward: ["Hospital", "Mabatini", "Huruma", "Ngei", "Mlango Kubwa", "Kiamaiko"] },
      ],
    },
    {
      name: "Turkana",
      subCounty: [
        { name: "Turkana Central", ward: ["Lodwar Township", "Kanamkemer", "Kalokol", "Kangatotha"] },
        { name: "Turkana North", ward: ["Kaeris", "Lake Zone", "Lapur", "Kaaleng/Kaikor"] },
        { name: "Turkana West", ward: ["Kakuma", "Lopur", "Letea", "Songot", "Kalobeyei"] },
        { name: "Turkana East", ward: ["Kapedo/Napeitom", "Katilia", "Lokori/Kochodin"] },
        { name: "Turkana South", ward: ["Kaputir", "Katilu", "Lobokat", "Kalapata"] },
        { name: "Loima", ward: ["Loima", "Lobei/Kotaruk", "Turkwel", "Loya/Puch"] },
      ],
    },
    {
      name: "West Pokot",
      subCounty: [
        { name: "Kapenguria", ward: ["Riwo", "Kapenguria", "Mnagei", "Siyoi", "Endugh"] },
        { name: "Sigor", ward: ["Wei Wei", "Lomut", "Masol", "Sekerr"] },
        { name: "Pokot South", ward: ["Kipkomot", "Sigor", "Tapach", "Batei"] },
        { name: "Kacheliba", ward: ["Suam", "Kodich", "Kasei", "Kapchok"] },
      ],
    },
    {
      name: "Samburu",
      subCounty: [
        { name: "Samburu West", ward: ["Lodokejek", "Suguta Marmar", "Maralal", "Loosuk"] },
        { name: "Samburu North", ward: ["El-Barta", "Nachola", "Ndoto", "Nyiro", "Angata Nanyokie"] },
        { name: "Samburu East", ward: ["Wamba West", "Wamba East", "Wamba North"] },
      ],
    },
    {
      name: "Trans Nzoia",
      subCounty: [
        { name: "Kiminini", ward: ["Kiminini", "Waitaluk", "Sirende", "Hospital", "Sikhendu"] },
        { name: "Endebess", ward: ["Endebess", "Matumbei", "Chepchoina"] },
        { name: "Saboti", ward: ["Kinyoro", "Matisi", "Tuwani", "Saboti", "Machewa"] },
        { name: "Cherangany", ward: ["Sitatunga", "Kaplamai", "Motosiet", "Cherangany/Suwerwa"] },
        { name: "Kwanza", ward: ["Kwanza", "Keiyo", "Bidii", "Kapomboi"] },
      ],
    },
    {
      name: "Uasin Gishu",
      subCounty: [
        { name: "Soy", ward: ["Mois Bridge", "Kapkures", "Ziwa", "Segero/Barsombe", "Kipsomba"] },
        { name: "Turbo", ward: ["Ngenyilel", "Tapsagoi", "Kamagut", "Kiplombe", "Huruma"] },
        { name: "Moiben", ward: ["Tembelio", "Sergoit", "Karuna/Meibeki", "Moiben"] },
        { name: "Ainabkoi", ward: ["Kapsoya", "Kaptagat", "Ainabkoi/Olare"] },
        { name: "Kapseret", ward: ["Simat/Kapseret", "Kipkenyo", "Megun", "Langas"] },
        { name: "Kesses", ward: ["Race Course", "Cheptiret/Kipchamo", "Tulwet/Chuiyat", "Tarakwa"] },
      ],
    },
    {
      name: "Elgeyo-Marakwet",
      subCounty: [
        { name: "Marakwet East", ward: ["Kapyego", "Sambirir", "Endo", "Embobut / Embulot"] },
        { name: "Marakwet West", ward: ["Lelan", "Sengwer", "Cherang'any/Chebororwa", "Moiben/Kuserwo"] },
        { name: "Keiyo North", ward: ["Emsoo", "Kamarin", "Kaptarakwa", "Tambach"] },
        { name: "Keiyo South", ward: ["Kiptuilong", "Metkei", "Chepkorio", "Soy South"] },
      ],
    },
    {
      name: "Nandi",
      subCounty: [
        { name: "Tinderet", ward: ["Songhor/Soba", "Tindiret", "Chemelil/Chemase", "Kapsimotwo"] },
        { name: "Aldai", ward: ["Kabwareng", "Terik", "Kemeloi-Maraba", "Kobujoi", "Kaptumo-Kaboi"] },
        { name: "Nandi Hills", ward: ["Nandi Hills", "Chepkunyuk", "Ol'Lessos", "Kapchorua"] },
        { name: "Chesumei", ward: ["Chemundu/Kapngetuny", "Kosirai", "Lelmokwo/Ngechek", "Kaptel/Kamoiywo"] },
        { name: "Emgwen", ward: ["Kapkanani", "Kilibwoni", "Chepkumia", "Kapsabet"] },
        { name: "Mosop", ward: ["Kipkaren", "Kurgung/Surungai", "Kabiyet", "Ndalat", "Chepterwai"] },
      ],
    },
    {
      name: "Baringo",
      subCounty: [
        { name: "Baringo Central", ward: ["Kabarnet", "Sacho", "Tenges", "Ewalel/Chapchap"] },
        { name: "Baringo North", ward: ["Barwessa", "Kabartonjo", "Saimo/Kipsaraman", "Saimo/Soi"] },
        { name: "Baringo South", ward: ["Marigat", "Ilchamus", "Mochongoi", "Mukutani"] },
        { name: "Mogotio", ward: ["Mogotio", "Emining", "Kisanana"] },
        { name: "Eldama Ravine", ward: ["Lembus", "Lembus Kwen", "Ravine", "Mumberes/Maji Mazuri"] },
        { name: "Tiaty", ward: ["Tirioko", "Kolowa", "Ribkwo", "Silale", "Loyamorok"] },
      ],
    },
    {
      name: "Laikipia",
      subCounty: [
        { name: "Laikipia West", ward: ["Ol-Moran", "Rumuruti Town", "Githiga", "Marmanet", "Igwamiti"] },
        { name: "Laikipia East", ward: ["Ngabit", "Tigithi", "Umande", "Nanyuki"] },
        { name: "Laikipia North", ward: ["Sosian", "Segera", "Mugogodo West", "Mugogodo East"] },
      ],
    },
    {
      name: "Nakuru",
      subCounty: [
        { name: "Nakuru East", ward: ["Biashara", "Kivumbini", "Flamingo", "Menengai", "Nakuru East"] },
        { name: "Nakuru West", ward: ["Barut", "London", "Kaptembwo", "Kapkures", "Rhoda"] },
        { name: "Naivasha", ward: ["Biashara", "Hell's Gate", "Lake View", "Mai Mahiu", "Maeilla", "Olkaria"] },
        { name: "Gilgil", ward: ["Gilgil", "Elementaita", "Mbaruk/Eburu", "Malewa West", "Murindat"] },
        { name: "Molo", ward: ["Mariashoni", "Elburgon", "Turi", "Molo"] },
        { name: "Njoro", ward: ["Mau Narok", "Mauche", "Kihingo", "Nessuit", "Lare", "Njoro"] },
        { name: "Rongai", ward: ["Menengai West", "Soin", "Visoi", "Mosop", "Solai"] },
        { name: "Subukia", ward: ["Subukia", "Waseges", "Kabazi"] },
        { name: "Kuresoi North", ward: ["Kiptororo", "Nyota", "Sirikwa", "Kamara"] },
        { name: "Kuresoi South", ward: ["Amalo", "Keringet", "Kiptagich", "Tinet"] },
        { name: "Bahati", ward: ["Bahati", "Kiamaina", "Lanet/Umoja", "Dundori", "Kabatini"] },
      ],
    },
    {
      name: "Narok",
      subCounty: [
        { name: "Narok North", ward: ["Olpusimoru", "Olokurto", "Narok Town", "Nkareta", "Olorropil"] },
        { name: "Narok South", ward: ["Majimoto/Naroosura", "Ololulung'a", "Melelo", "Sagamian"] },
        { name: "Narok East", ward: ["Mosiro", "Ildamat", "Keekonyokie", "Suswa"] },
        { name: "Narok West", ward: ["Ilmotiok", "Mara", "Siana", "Naikarra"] },
        { name: "Kilgoris", ward: ["Kilgoris Central", "Keyian", "Angata Barikoi", "Shankoe"] },
        { name: "Emurua Dikirr", ward: ["Ilkerin", "Ololmasani", "Mogondo", "Kapsasian"] },
      ],
    },
    {
      name: "Kajiado",
      subCounty: [
        { name: "Kajiado Central", ward: ["Purko", "Ildamat", "Dalalekutuk", "Matapato North", "Matapato South"] },
        { name: "Kajiado North", ward: ["Olkeri", "Ongata Rongai", "Nkaimurunya", "Oloolua", "Ngong"] },
        { name: "Kajiado East", ward: ["Kaputiei North", "Kitengela", "Oloosirkon/Sholinke", "Kenyewa-Poka"] },
        { name: "Kajiado West", ward: ["Keekonyokie", "Iloodokilani", "Magadi", "Ewuaso Oonkidong'i"] },
        { name: "Kajiado South", ward: ["Entonet/Lenkisim", "Mbirikani/Eselengei", "Kimana", "Imbirikani"] },
      ],
    },
    {
      name: "Kericho",
      subCounty: [
        { name: "Ainamoi", ward: ["Kapkugerwet", "Ainamoi", "Kipchimchim", "Kipchebor"] },
        { name: "Belgut", ward: ["Waldai", "Kabianga", "Cheboin", "Chaik"] },
        { name: "Sigowet/Soin", ward: ["Sigowet", "Soin", "Soliot", "Kaplelartet"] },
        { name: "Kipkelion East", ward: ["Londiani", "Kedowa/Sample", "Chepseon"] },
        { name: "Kipkelion West", ward: ["Kunyak", "Kamasian", "Kipkelion", "Chilchila"] },
        { name: "Bureti", ward: ["Kisiara", "Tebesonik", "Cheboin", "Chemosot"] },
      ],
    },
    {
      name: "Bomet",
      subCounty: [
        { name: "Bomet Central", ward: ["Siloibwet", "Singorwet", "Ndaraweta", "Chesoen", "Mutarakwa"] },
        { name: "Bomet East", ward: ["Longisa", "Kembu", "Chemaner", "Merigi", "Kipreres"] },
        { name: "Chepalungu", ward: ["Kong'asis", "Nyangores", "Sigor", "Chebunyo", "Siongiroi"] },
        { name: "Sotik", ward: ["Ndanai/Abosi", "Kipsonoi", "Kapletundo", "Chemogel"] },
        { name: "Konoin", ward: ["Kimulot", "Mogogosiek", "Boito", "Embomos", "Chechiat"] },
      ],
    },
    {
      name: "Kakamega",
      subCounty: [
        { name: "Lurambi", ward: ["Butsotso South", "Butsotso Central", "Butsotso East", "Sheywe", "Mahiakalo", "Shirere"] },
        { name: "Mumias West", ward: ["Mumias Central", "Mumias North", "Etenje", "Musanda"] },
        { name: "Mumias East", ward: ["Lusheya/Lubinu", "Maluha/Isongo/Makunga", "East Wanga"] },
        { name: "Matungu", ward: ["Koyonzo", "Mayoni", "Kholera", "Khalaba", "Namamali"] },
        { name: "Butere", ward: ["Marama West", "Marama Central", "Marama South", "Marenyo/Shianda"] },
        { name: "Khwisero", ward: ["Kisa North", "Kisa West", "Kisa Central", "Kisa East"] },
        { name: "Shinyalu", ward: ["Isukha North", "Isukha Central", "Isukha South", "Isukha East", "Isukha West"] },
        { name: "Ikolomani", ward: ["Idakho South", "Idakho East", "Idakho Central"] },
        { name: "Lugari", ward: ["Mautuma", "Lugari", "Lumakanda", "Chekalini", "Chevaywa", "Lwandeti"] },
        { name: "Likuyani", ward: ["Likuyani", "Sango", "Kongoni", "Nzoia", "Sinoko"] },
        { name: "Malava", ward: ["West Kabras", "Chemuche", "East Kabras", "Butali/Chegulo", "Manda-Shivanga"] },
        { name: "Navakholo", ward: ["Ingotse-Matiha", "Shinoyi-Shikomari-Esumeyia", "Bunyala West", "Bunyala East"] },
      ],
    },
    {
      name: "Vihiga",
      subCounty: [
        { name: "Vihiga", ward: ["Lugaga-Wamuluma", "South Maragoli", "Central Maragoli", "Mungoma"] },
        { name: "Sabatia", ward: ["Lyaduywa/Izava", "West Sabatia", "Chavakali", "North Maragoli"] },
        { name: "Hamisi", ward: ["Shiru", "Gisambai", "Shamakhokho", "Banja", "Tambua"] },
        { name: "Luanda", ward: ["Luanda Township", "Wemilabi", "Mwibona", "Luanda South"] },
        { name: "Emuhaya", ward: ["North East Bunyala", "Central Bunyala", "West Bunyala"] },
      ],
    },
    {
      name: "Bungoma",
      subCounty: [
        { name: "Kanduyi", ward: ["Bukembe West", "Bukembe East", "Township", "Khalaba", "Musikoma", "Tuuti/Marakaru", "Sang'alo Central"] },
        { name: "Bumula", ward: ["Bumula", "Khasoko", "Kabula", "West Bukusu", "South Bukusu"] },
        { name: "Webuye West", ward: ["Sitikho", "Matulo", "Misikhu", "Bokoli"] },
        { name: "Webuye East", ward: ["Mihuu", "Ndivisi", "Maraka"] },
        { name: "Kimilili", ward: ["Kibingei", "Kimilili", "Maeni", "Kamukuywa"] },
        { name: "Tongaren", ward: ["Mbakalo", "Naitiri/Kabuyefwe", "Milima", "Ndalu", "Tongaren", "Soysambu"] },
        { name: "Sirisia", ward: ["Namwela", "Malakisi/South Kulisiru", "Lwandanyi"] },
        { name: "Kabuchai", ward: ["Kabuchai/Chwele", "West Nalondo", "Bwake/Luuya", "Mukuyuni"] },
        { name: "Mt. Elgon", ward: ["Cheptais", "Chesikaki", "Chepyuk", "Kapkateny", "Kaptama", "Elgon"] },
      ],
    },
    {
      name: "Busia",
      subCounty: [
        { name: "Matayos", ward: ["Bukhayo West", "Mayenje", "Matayos South", "Busia Township"] },
        { name: "Teso North", ward: ["Malaba Central", "Malaba North", "Malaba South", "Ang'urai South", "Ang'urai North", "Ang'urai East"] },
        { name: "Teso South", ward: ["Ang'orom", "Chakol South", "Chakol North", "Amukura West", "Amukura Central", "Amukura East"] },
        { name: "Nambale", ward: ["Nambale Township", "Bukhayo North/Walatsi", "Bukhayo East"] },
        { name: "Butula", ward: ["Marachi West", "Marachi Central", "Marachi East", "Marachi North"] },
        { name: "Funyula", ward: ["Namboboto Nambuku", "Nangina", "Ageng'a Nanguba", "Bwiri"] },
        { name: "Budalangi", ward: ["Bunyala Central", "Bunyala North", "Bunyala West", "Bunyala South"] },
      ],
    },
    {
      name: "Siaya",
      subCounty: [
        { name: "Alego Usonga", ward: ["Siaya Township", "North Alego", "Central Alego", "West Alego", "South Alego"] },
        { name: "Gem", ward: ["North Gem", "West Gem", "Central Gem", "Yala Township", "East Gem", "South Gem"] },
        { name: "Ugenya", ward: ["West Ugenya", "Ukwala", "North Ugenya", "East Ugenya"] },
        { name: "Ugunja", ward: ["Sidindi", "Sigomere", "Ugunja"] },
        { name: "Bondo", ward: ["Central Sakwa", "South Sakwa", "Yimbo West", "Yimbo East", "West Sakwa", "North Sakwa"] },
        { name: "Rarieda", ward: ["North Uyoma", "South Uyoma", "West Madiany", "East Madiany", "West Uyoma"] },
      ],
    },
    {
      name: "Kisumu",
      subCounty: [
        { name: "Kisumu Central", ward: ["Railways", "Shaurimoyo Kaloleni", "Market Milimani", "Kondele", "Nyalenda B"] },
        { name: "Kisumu East", ward: ["Kajulu", "Manyatta B", "Nyalenda A", "Kolwa East", "Kolwa Central"] },
        { name: "Kisumu West", ward: ["South West Kisumu", "Central Kisumu", "Kisumu North", "West Kisumu", "North West Kisumu"] },
        { name: "Seme", ward: ["West Seme", "Central Seme", "East Seme", "North Seme"] },
        { name: "Nyando", ward: ["East Kano/Wawidhi", "Ahero", "Kabonyo/Kanyagwal", "Kobura", "Onjiko"] },
        { name: "Muhoroni", ward: ["Miwani", "Ombeyi", "Masogo/Nyang'oma", "Muhoroni/Koru", "Chemelil"] },
        { name: "Nyakach", ward: ["South West Nyakach", "North Nyakach", "Central Nyakach", "West Nyakach", "South East Nyakach"] },
      ],
    },
    {
      name: "Homa Bay",
      subCounty: [
        { name: "Homa Bay Town", ward: ["Homa Bay Central", "Homa Bay West", "Homa Bay East"] },
        { name: "Rangwe", ward: ["West Kano/Wawidhi", "Kagan", "Kochia", "Central Rangwe"] },
        { name: "Ndhiwa", ward: ["Kwach", "Kanyadoto", "Kanyikela", "North Kabuoch", "South Kabuoch", "Kanyamwa Kologi", "Kanyamwa Kosewe"] },
        { name: "Mbita", ward: ["Mfangano Island", "Rusinga Island", "Kasgunga", "Gembe"] },
        { name: "Suba North", ward: ["Lambwe", "Mbita", "Rusinga", "Mfangano"] },
        { name: "Suba South", ward: ["Gwassi South", "Gwassi North", "Kaksingri West", "Ruma Kaksingri"] },
        { name: "Karachuonyo", ward: ["West Karachuonyo", "North Karachuonyo", "Central Karachuonyo", "Kanyaluo", "Kibiri", "Wang'chieng", "Kendubay Town"] },
        { name: "Kasipul", ward: ["West Kasipul", "South Kasipul", "Central Kasipul", "East Kasipul", "West Kamagak"] },
        { name: "Kabondo Kasipul", ward: ["Kabondo East", "Kabondo West", "Kokwanyo/Kakelo", "Kojwach"] },
      ],
    },
    {
      name: "Migori",
      subCounty: [
        { name: "Suna East", ward: ["God Jope", "Suna Central", "Kakrao", "Kwa"] },
        { name: "Suna West", ward: ["Wiga", "Wasimbete", "Ragana-Oruba", "Wasweta II"] },
        { name: "Nyatike", ward: ["Kachien'g", "Kanyasa", "North Kadem", "Macalder/Kanyarwanda", "Kaler", "Got Kachola", "Muhuru"] },
        { name: "Kuria West", ward: ["Bukira East", "Bukira Central/Ikerege", "Isibania", "Makamero", "Tagare", "Nyamosuru/Mabera"] },
        { name: "Kuria East", ward: ["Gokeharaka/Getambwega", "Ntimaru West", "Ntimaru East", "Nyabasi East", "Nyabasi West"] },
        { name: "Rongo", ward: ["North Kamagambo", "Central Kamagambo", "East Kamagambo", "South Kamagambo"] },
        { name: "Awendo", ward: ["North Sakwa", "South Sakwa", "West Sakwa", "Central Sakwa"] },
        { name: "Uriri", ward: ["West Kanyamkago", "North Kanyamkago", "Central Kanyamkago", "South Kanyamkago", "East Kanyamkago"] },
      ],
    },
    {
      name: "Kisii",
      subCounty: [
        { name: "Kitutu Chache North", ward: ["Monyerero", "Sensi", "Marani", "Mwamonari"] },
        { name: "Kitutu Chache South", ward: ["Bogeka", "Nyatieko", "Nyakoe", "Kitutu Central", "Nyabusaro"] },
        { name: "Nyaribari Chache", ward: ["Birongo", "Keumbu", "Kiogoro", "Ibeno", "Central Ward"] },
        { name: "Nyaribari Masaba", ward: ["Ichuni", "Nyamasibi", "Masimba", "Gesusu", "Kiamokama"] },
        { name: "South Mugirango", ward: ["Bogetenga", "Borabu / Chitago", "Moticho", "Getenga"] },
        { name: "Bomachoge Borabu", ward: ["Bombaba Borabu", "Boochi Borabu", "Bokimonge", "Magenche"] },
        { name: "Bomachoge Chache", ward: ["Majoge Bassi", "Boochi / Tendere", "Bosoti / Sengera"] },
        { name: "Bobasi", ward: ["Masige West", "Masige East", "Bassi Central", "Nyacheki", "Bassi Bogetaorio"] },
        { name: "Bonchari", ward: ["Bomariba", "Bogiakumu", "Bomorenda", "Riana"] },
      ],
    },
    {
      name: "Nyamira",
      subCounty: [
        { name: "West Mugirango", ward: ["Nyamaiya", "Bogichora", "Bosamaro", "Bonyamatuta", "Township"] },
        { name: "North Mugirango", ward: ["Itibo", "Bomwagamo", "Bokeira", "Magwagwa", "Ekerenyo"] },
        { name: "Borabu", ward: ["Mekene", "Monyerero", "Esise", "Nyansiongo"] },
        { name: "Kitutu Masaba", ward: ["Rigoma", "Gachuba", "Kemera", "Magombo", "Manga", "Gesima"] },
      ],
    },
  ] as const
}